import json
filename = 'people_united_schema_mongo_id.json'


people_model = {
    "_id": "recv0dAY2ULzJ687g",
    "status": None,
    "fields": {
        "personLookup": "aaron_1",
        "personID": 1,
        "name": "Aaron",
        "name_ar": "",
        "surname": None,
        "surname_ar": None,
        "alsoCalled": None,
        "alsoCalled_ar": None,
        "isProperName": True,
        "gender": "Male",
        "memberOf": ["recuYvXjZsXumRLPL"],
        "birthPlace": ["recfrXyxhuYOczKTm"],
        "verses": [
            "rec9zZSdb798FoFX8",
            "rec6yK7UZdtfxfXKO",
            "rec9PPoA12Z9QA1Qy",
            "recQ4BCdXHu9AiPxP",
            "recnaS6Ph798q5Z6Q",
            "rec12m5c1ChHMI9Jp",
            "recwvRLQPduTfeHqD",
            "receB5zEcduDQPmol",
            "recxvyuwU6v5m1tKI",
            "recEvdKEepkTNGpRT",
            "recdaQAjmKUgoWrvH",
            "recWrAMjgU1SZmJHR",
            "recMdfsvE7pihuH2h",
            "recIrp2uRjL6cn7fp",
            "recdnX3XcmeYbsr0M",
            "rechjKTHqlRNRePT9",
            "recOQ1tEfeehpEDE3",
            "recmDRsM2utlLwRem",
            "rec97rPoJWIikLbM2",
            "rec9LNSzH2KSxNxxy",
            "recL5S1unH9BqjBOt",
            "recmEoJHNVdKzCUyq",
            "recm13mJv278YZQzP",
            "recDRnzwPiMDMqlHS",
            "recSmOYjvvJtEgOjf",
            "reclLQ24mUHLamDhX",
            "recPYMnIRpBYaEEcP",
            "recOiAe4KD8J1KQs8",
            "rec2tUBK5zTaCKqi1",
            "rec1s5aOgR1nJiTzA",
            "recAW8YxCuPTsRV0u",
            "recBBfS4IrjG5U6C4",
            "rec1ZImoRZAI9RqZf",
            "recAlRNI1FepLwxxH",
            "recZZKctazif0AiGA",
            "rec9v7YKKL3ov3bt1",
            "recWre9uC7F2pFSI2",
            "recvbhVHwgVjBMJpc",
            "recKZlYsbCTSwKEHx",
            "recu6STbjVugYYNx3",
            "rec0MtJJcjggaA8v5",
            "recyYxLxKDIrw7lIj",
            "reckFlzZSEykNmuge",
            "recm8hF6AgAHp4OKU",
            "recJTEFhpEVDwSo6s",
            "recf8jghBtrb9C9DT",
            "reco9S8WcUhqUFAJQ",
            "recLgK0a2tlTctDrp",
            "recx5WKkgQoOeGJVL",
            "recrIB1pDJIYNUf8i",
            "recFfJ5ZhyqKvSw2l",
            "recP431OOavRBiE3M",
            "rechOchmWdHpOF8Q7",
            "recsir33dDmnaXC5o",
            "recC6f7RGI4kzN6Vo",
            "rechrvlQSWPRGqciI",
            "reccDnCWC79MTaCtZ",
            "recWjXhkUt1wx2Scj",
            "recUtbB82IqchPEWb",
            "recWtGk0iKSDASjnT",
            "recckcCk2Z1qxXhmn",
            "reciVkVBD9XDDDrQp",
            "reczROXyM52l2ynLw",
            "recNHBgh7vC4q1uoL",
            "reccfDvdlti6fSW3f",
            "recvkP5t4plGjwTcG",
            "recVAizq6igWXWfya",
            "recTImgA28IK9lF8f",
            "recLnMgXy9tmzTnMA",
            "recS6hRDQfy7PiKDz",
            "rec41Kh1qiGFqWdLT",
            "recFOWHFGj4dHWeLb",
            "rec4TGdfh1ZJrCGT9",
            "recYRoYNP4L71AIo9",
            "recHVr7EvWBmoK17J",
            "recPq5X4NahmEW10E",
            "recUrUQlIKzxo6UAT",
            "recK61Oatq2TQmOJg",
            "rec8YLNViaww1o7sm",
            "rec4VQNxEwPucsm9I",
            "recs66jeUn73L4M6Z",
            "recb8B6vBaYldS9sq",
            "recU7UtBKVEKEEDPd",
            "recOfXLzGzGa9VFCH",
            "recxsHLs2L9DsryLD",
            "recmvtp5RNvwuGBGt",
            "rece7e3eKhtcd30Mr",
            "recbOLJ23iXwIp3eO",
            "recgcvZmi1Y0PyXKd",
            "recxTF2UUbSUv7V71",
            "recoH7eVtCXDV4Fgy",
            "recIlmi8hSJfHNcSh",
            "recBJseUYNZqC5gJj",
            "recGoUfhRBhsQxCG5",
            "recMxOf5B445ldnlP",
            "reczvO8i8d9TmxUXK",
            "recAxj0q1F1LZkyoV",
            "recJyidWqqZldsO7b",
            "rec8ewINKmNjYdAN8",
            "recm2qj1uz4XNH6LQ",
            "recIA7FyfDybWIbXu",
            "recQj5bKxja0wJFxe",
            "recuHCV6V3oIrlTSq",
            "rec4cdrbDFP2rtT0w",
            "rec970Qfc6qdvZt7s",
            "recsB381rdc6nq6Ev",
            "recKhZjU7zfrcZnGX",
            "recGYfzqnBnI84AKy",
            "rec0ROh6IUzfNBMuT",
            "recaOaKVci0GHhwur",
            "recS4YFq4VKpfq96x",
            "recIBYStCZF2V3wLr",
            "recwXt6FykEL2Hjzl",
            "recEiAjEUMwkFfMX1",
            "recvuP41dPH6R2wTU",
            "recFHfxpsPP2sv9dk",
            "recgjGmHXj7GIyzmM",
            "recaJx2G0OjcvN11j",
            "recmR0HwXi17w6MQN",
            "reciwD8fODOpYTNUi",
            "recH5Ql5sj0tZ4Aku",
            "rec29kQEVA0pxAA8w",
            "rec6s7SJVO6JPba1Q",
            "recrJOZbiUssebxcD",
            "recyAZb3jaNKe3ud0",
            "recIEzuRKPahFyxhS",
            "recCajVokjepMB1FC",
            "recUf0xMr4MtLcUuz",
            "recJK5o2T7PQY8dVN",
            "reccMmodIXXEshoEd",
            "rec8196QjlW1QSj1o",
            "recHp76P1Loz32d1H",
            "reckswrqIqbYMAdKX",
            "rec71QwhAzbWSSmCS",
            "recNojDQmyoV5mg2p",
            "recjFvXpuY0SiK9i3",
            "recB3dwrqNC7zutBJ",
            "recajKZwVXMZOuH8l",
            "recOUFFTcHsE2bRIH",
            "recHz2jbHQyqLyluG",
            "rec58cLj5cq0C4js9",
            "recqnyVjIwK50cHxX",
            "recK3BFwXDcfaBwJ7",
            "reccL35VyCghQj56u",
            "recae4nJmDhuHoWxZ",
            "recuddXG4SxCT5F1j",
            "recRQow4wuCerMoUH",
            "recfvSt9ciou57CpT",
            "rec2Vb9OstoRwC9eJ",
            "recCT0kACKsfWO0Tf",
            "recBb8DziFN4hhvTh",
            "recbL0rBWYmg0SaNI",
            "recY55pOYheibLosO",
            "recfCmjJSawyLaqdt",
            "recknTGW34XpVvBIg",
            "recY0PVjpF1fAbBZq",
            "rec7gAsD7bvF58sOQ",
            "recYqNWiKGHPnq7Ql",
            "rec4Ui74sL8eUU4UB",
            "recGuLhXRCuzktTBf",
            "recQfNeXyP5AfTBJM",
            "rechjTtsRMZ7jrNBf",
            "recXThq8egWpUtOvQ",
            "recLI0XtQdTNhjEFA",
            "reccAq2R23YEI7Ylo",
            "recEOIJN1a95lP7xU",
            "reczxl0oqkMPbP51b",
            "recAt6OkQLLwEPYI0",
            "recGlGOkvDp3JDorM",
            "recCUCYf7VDIEq0Io",
            "recjclT7P046qp9Yc",
            "rechE0gZfDDNh4ua0",
            "recbCb5I7aiaZVa8s",
            "recBfLf4DYxZewYPI",
            "recHKFxZLKJFaDIfB",
            "recIUCsli7rvX4TAd",
            "recRd3jgtBGwvR4ET",
            "recxeZDE7I4cldcPK",
            "rec6AszoSDXBWPdTo",
            "recWHFyTAehwVfnMC",
            "recCOvX7oqadZJfcV",
            "recgMAsIEgrH6uKgN",
            "recGkbZHdzkSdU8jV",
            "recaTDBXFCAgXhdPF",
            "recgMv2erbJFOsDX4",
            "recSx8ARF6QqxsRkC",
            "rec1DD5rs1bOF8C2W",
            "rec8c17hnbKhVol7P",
            "recpAF66pPrKDqEjx",
            "recuYzMJ1oGGIbKBr",
            "recVMTthAl7lWvOQL",
            "recKeuth44Em6snhm",
            "recoLdkXTxdSwzWD5",
            "recBdnANWMmiQrU9u",
            "recq56fIj0qPWW8Fj",
            "recxO2OOcaAteBtvj",
            "recFixrCtCaKSc1IJ",
            "recBaLGIwxxDxhJyR",
            "recjiawHYEaDamw5k",
            "rec5bmeS0DCK67w20",
            "recGqfqRCaPsuaVeO",
            "recnN1d6o268NzWty",
            "recIcrx0RDtrsMNgl",
            "rec5W4HDh0UDpEd3S",
            "recH7TgcCLRElicpn",
            "rec7rn181bF6T0sHx",
            "recqmFxbUHbvxGEOk",
            "recCKRPIL9MtapoSY",
            "recldL6fALm4sfMPv",
            "recaV9YioiO6pZetw",
            "recFTMDgCYasoBI99",
            "recL1lmeOrvwQG8Yd",
            "recIlV32mQUuA1u3W",
            "recoIF3HN8YlFPJPz",
            "rec7cTZONQOtMIm8r",
            "recDTBxGyODlLeoif",
            "recSIJZtBTsXnPV5T",
            "recrgQ1fJ3eHShEWz",
            "recMpp4wcCo7FE794",
            "recaX31C4o4mEdfCt",
            "recspqee3FBCag9iy",
            "rec0lnkIpYvYxkHPD",
            "recnF2s2DCR1dd9i3",
            "recSKqBUrkzj5TzoA",
            "recviIX7UchtFkbdM",
            "recgAj5B6lKyTMb1h",
            "recjpnsDMHF6mRNdw",
            "recOZU1eIzfY3F4gB",
            "rec4uuPpuRGP1pO4y",
            "recGKOojiRi4EGd7t",
            "recfOjZgY8kuyQVbb",
            "recayLKPJFgeCfmzR",
            "recrLhqB0NxCst22U",
            "reccwoBABbxtCFqnn",
            "reciOGCoNpYzjO7Os",
            "recI7QS0opfAZ2NYe",
            "recY6SiHvm1Rem0Wo",
            "recmCcRsd9wgcDB0Z",
            "rec7UmhvupWnDSjjU",
            "rec4nssowrKodnIXl",
            "rech0n6FYpyP7Uog7",
            "recywO2fSQlJLggoi",
            "recR3zLIMoeTWwlWh",
            "rec0VRK6epvniQ24s",
            "recyfzJRzEiWbE8XC",
            "recWEv1L5tfMxdeIW",
            "recdqdIUX53jvBQMB",
            "rec8dMnPgDfzFZPR7",
            "rec5on0NojE8lyEVA",
            "reczMLMPxjDABCTLG",
            "recvNddRYVnxrsYdx",
            "recA8kBX3VBtBsMvR",
            "recodXuYPQz0MGrgE",
            "recCPEZOh6g4MfYR0",
            "recdUDx9Q9gLHpXhh",
            "recaUJfyWheUMDnUF",
            "rec8lPLNMJcdRO0mQ",
            "recGhF9MTaMVNm2LU",
            "rec9f67RVa8HXrW8e",
            "rect1yj4fOUC3kHST",
            "recCJrkzV3nO9JtNe",
            "recc5W9jUqu1SDwdd",
            "rect6hyLyMkF6SVED",
            "recMKrq3sOMY1Ciy6",
            "rec9e7U4ET045mQQv",
            "recpNdyqSnZMcUrng",
            "recde94u4PpxHyevr",
            "recdmOirsMJM5cN8P",
            "recDrPDSG4lvfnYWq",
            "rec2TBbN5yGjy8cxw",
            "recex9SsPjcPVjrf7",
            "recOSWfr2kiHXh5pn",
            "recez7Oiz0Qll6fSX",
            "recRjUT0hJFHqZW0S",
            "recb4c8vdNWxYy0bk",
            "recVGdF6DJle1pfnq",
            "recUznb5iicjgXqDd",
            "recWtjQKSXeyFjbKK",
            "recO1C4UlgiyAb4Zp",
            "recGWhP9LCsHH8TzN",
            "recKsNg5mgM8Pfgjx",
            "recBgy5WXcnZeppDj",
            "rechHsm6ndLMWXin5",
            "recF956mIvujSi4B9",
            "recsnUYSw9OLnMzJy",
            "recEsLDpwiMFIwjcV",
            "recAGedGm4nUKQRhF",
            "recC5AqR4uTVElKel",
            "recDN2mz6cmxw9cNM",
            "recudwQX5A7YnbGx7",
            "rece9opjyXqnrDRrN",
            "recVY0D3fJy7UmnLN",
            "rech6tAmV7GZF356B",
            "recMOfqiXqpit0T9W",
            "recbgFzRzLDEGFsD9",
            "recm7kUpiBTruTfbQ",
            "recLYPtTxpyc73S6l",
            "recLAhcdPSQJRM7ta",
            "rec2uUyG1HysIfbtw",
            "recZYTQGbNMU8dSCe",
            "rec3SVd8EoEIWJc5Y",
            "recoS5mGV9cJvnmuE",
            "recuT2esLpZzPy1bV",
            "recIeHiFiDkDY8pV6",
            "recjmdSsphdYABWvc",
            "rec4GFHiYEtO7TI9u",
            "reci3607sVd3tpk0q",
            "rec0LcIGajCwdTTp4",
            "recyRg3YFIlUq2WEH",
            "recV28eOLA8LU6znr",
            "recK2xBDYbfAtkedj",
            "recpBkhziWXKa4ZqB",
            "rec1thkoWgXsz302q",
            "recWXOE1kvAji0xey",
            "recURnLWuP39guPq4",
            "recwFmRC65eey6AFb",
            "recoNXTUZFbAdIsvz",
            "recMULiMFc1dBYuTl",
            "rectaEuVQ0j6eswMJ",
            "reclEogvAHsYKyl10",
            "recQlnQKTQdUmjZVT",
            "recv15MP6b5APjvxD",
            "recwwyAzg9omPdCLL",
            "reccINuczVPaIrQzu",
            "recSTLid15rz1lSMX",
            "rec8t2x8TZAq11fRx",
            "rect4RMLvqaXhSBv9",
            "rec6IiYTbzKxGbpbF",
            "recZh9OEoRRFg1uAk",
            "recLF4QJHRRlFndu1",
            "rec5d0D7TRFktLFLO"
        ],
        "siblings": ["recvZksoA0NmFrYZ7", "recjNRR60PAuFtjha"],
        "halfSiblingsSameFather": None,
        "halfSiblingsSameMother": None,
        "mother": ["recxqmePpZGwvUF06"],
        "father": ["recPXtuWYdjyghv7R"],
        "children": [
            "rec2LyU5fsvL5DWDi",
            "recyDlo13a3T5DDGh",
            "recCSN4kRre7qWV1P",
            "recOXtCZgcG7YobCm"
        ],
        "partners": ["rec7jlnTi8vIXmZyO"],
        "displayTitle": "Aaron",
        "displayTitle_ar": "",
        "status": "publish",
        "ambiguous": None,
        "Disambiguation (temp)": None,
        "verseCount": 331,
        "minYear": -1700,
        "maxYear": 64,
        "birthYear": ["recR2mYAJh2BnwSdC"],
        "deathYear": ["recCf94cuWqDNmP9K"],
        "alphaGroup": "A",
        "alphaGroup_ar": None,
        "slug": "aaron_1",
        "Easton's Count": 1,
        "eastons": ["recQNbmhvjXqt0wHQ"],
        "events": None,
        "deathPlace": ["recn5ad7qKvkUdCyZ"],
        "chaptersWritten": None,
        "timeline": ["recjkmUO88wihv8Ci", "recr71Fz4NHTnGLJ2"],
        "eventGroups": None,
        "eventGroups_ar": None,
        "dictText": [
            "The eldest son of Amram and Jochebed, a daughter of Levi ([Ex. 6:20](/exod#Exod.6.20)). Some explain the name as meaning mountaineer, others mountain of strength, illuminator. He was born in Egypt three years before his brother Moses, and a number of years after his sister Miriam (2:1, 4; 7:7). He married Elisheba, the daughter of Amminadab of the house of Judah (6:23; [1 Chr. 2:10](/1chr#1Chr.2.10)), by whom he had four sons, Nadab and Abihu, Eleazar and Ithamar. When the time for the deliverance of Isarael out of Egypt drew nigh, he was sent by God ([Ex. 4:14](/exod#Exod.4.14), [27-30](/exod#Exod.4.27)) to meet his long-absent brother, that he might co-operate with him in all that they were required to do in bringing about the Exodus. He was to be the \u201cmouth\u201d or \u201cprophet\u201d of Moses, i.e., was to speak for him, because he was a man of a ready utterance (7:1, 2, 9, 10, 19). He was faithful to his trust, and stood by Moses in all his interviews with Pharaoh.\n\n When the ransomed tribes fought their first battle with Amalek in Rephidim, Moses stood on a hill overlooking the scene of the conflict with the rod of God in his outstretched hand. On this occasion he was attended by Aaron and Hur, his sister\u2019s husband, who held up his wearied hands till Joshua and the chosen warriors of Israel gained the victory (17:8-13).\n\n Afterwards, when encamped before Sinai, and when Moses at the command of God ascended the mount to receive the tables of the law, Aaron and his two sons, Nadab and Abihu, along with seventy of the elders of Israel, were permitted to accompany him part of the way, and to behold afar off the manifestation of the glory of Israel\u2019s God ([Ex. 19:24](/exod#Exod.19.24); [24:9-11](/exod#Exod.24.9)). While Moses remained on the mountain with God, Aaron returned unto the people; and yielding through fear, or ignorance, or instability of character, to their clamour, made unto them a golden calf, and set it up as an object of worship ([Ex. 32:4](/exod#Exod.32.4); [Ps. 106:19](/ps#Ps.106.19)). On the return of Moses to the camp, Aaron was sternly rebuked by him for the part he had acted in this matter; but he interceded for him before God, who forgave his sin ([Deut. 9:20](/deut#Deut.9.20)).\n\n On the mount, Moses received instructions regarding the system of worship which was to be set up among the people; and in accordance therewith Aaron and his sons were consecrated to the priest\u2019s office ([Lev. 8](/lev#Lev.8); [9](/lev#Lev.9)). Aaron, as high priest, held henceforth the prominent place appertaining to that office.\n\n When Israel had reached Hazeroth, in \u201cthe wilderness of Paran,\u201d Aaron joined with his sister Miriam in murmuring against Moses, \u201cbecause of the Ethiopian woman whom he had married,\u201d probably after the death of Zipporah. But the Lord vindicated his servant Moses, and punished Miriam with leprosy ([Num. 12](/num#Num.12)). Aaron acknowledged his own and his sister\u2019s guilt, and at the intercession of Moses they were forgiven.\n\n Twenty years after this, when the children of Israel were encamped in the wilderness of Paran, Korah, Dathan, and Abiram conspired against Aaron and his sons; but a fearful judgment from God fell upon them, and they were destroyed, and the next day thousands of the people also perished by a fierce pestilence, the ravages of which were only stayed by the interposition of Aaron ([Num. 16](/num#Num.16)). That there might be further evidence of the divine appointment of Aaron to the priestly office, the chiefs of the tribes were each required to bring to Moses a rod bearing on it the name of his tribe. And these, along with the rod of Aaron for the tribe of Levi, were laid up overnight in the tabernacle, and in the morning it was found that while the other rods remained unchanged, that of Aaron \u201cfor the house of Levi\u201d budded, blossomed, and yielded almonds ([Num. 17:1-10](/num#Num.17.1)). This rod was afterwards preserved in the tabernacle ([Heb. 9:4](/heb#Heb.9.4)) as a memorial of the divine attestation of his appointment to the priesthood.\n\n Aaron was implicated in the sin of his brother at Meribah ([Num. 20:8-13](/num#Num.20.8)), and on that account was not permitted to enter the Promised Land. When the tribes arrived at Mount Hor, \u201cin the edge of the land of Edom,\u201d at the command of God Moses led Aaron and his son Eleazar to the top of that mountain, in the sight of all the people. There he stripped Aaron of his priestly vestments, and put them upon Eleazar; and there Aaron died on the top of the mount, being 123 years old ([Num. 20:23-29](/num#Num.20.23). Comp. [Deut. 10:6](/deut#Deut.10.6); [32:50](/deut#Deut.32.50)), and was \u201cgathered unto his people.\u201d The people, \u201ceven all the house of Israel,\u201d mourned for him thirty days. Of Aaron\u2019s sons two survived him, Eleazar, whose family held the high-priesthood till the time of Eli; and Ithamar, in whose family, beginning with Eli, the high-priesthood was held till the time of Solomon. Aaron\u2019s other two sons had been struck dead ([Lev. 10:1](/lev#Lev.10.1), [2](/lev#Lev.10.2)) for the daring impiety of offering \u201cstrange fire\u201d on the alter of incense.\n\n The Arabs still show with veneration the traditionary site of Aaron\u2019s grave on one of the two summits of Mount Hor, which is marked by a Mohammedan chapel. His name is mentioned in the Koran, and there are found in the writings of the rabbins many fabulous stories regarding him.\n\n He was the first anointed priest. His descendants, \u201cthe house of Aaron,\u201d constituted the priesthood in general. In the time of David they were very numerous ([1 Chr. 12:27](/1chr#1Chr.12.27)). The other branches of the tribe of Levi held subordinate positions in connection with the sacred office. Aaron was a type of Christ in his official character as the high priest. His priesthood was a \u201cshadow of heavenly things,\u201d and was intended to lead the people of Israel to look forward to the time when \u201canother priest\u201d would arise \u201cafter the order of Melchizedek\u201d ([Heb. 6:20](/heb#Heb.6.20))."
        ],
        "dictText_ar": "",
        "dictionaryLink": "https://www.biblestudytools.com/dictionaries/eastons-bible-dictionary/aaron.html",
        "dictionaryText": " the eldest son of Amram and Jochebed, a daughter of Levi (  Exodus 6:20  ). Some explain the name as meaning mountaineer, others mountain of strength, illuminator. He was born in Egypt three years before his brother Moses, and a number of years after his sister Miriam (  Exodus 2:1   Exodus 2:4  ;   7:7  ). He married Elisheba, the daughter of Amminadab of the house of Judah (  6:23  ;   1\ufffdChronicles 2:10  ), by whom he had four sons, Nadab and Abihu, Eleazar and Ithamar. When the time for the deliverance of Isarael out of Egypt drew nigh, he was sent by God (  Exodus 4:14   Exodus 4:27-30  ) to meet his long-absent brother, that he might co-operate with him in all that they were required to do in bringing about the Exodus. He was to be the \"mouth\" or \"prophet\" of Moses, i.e., was to speak for him, because he was a man of a ready utterance (  Exodus 7:1   Exodus 7:2   Exodus 7:9   Exodus 7:10   Exodus 7:19  ). He was faithful to his trust, and stood by Moses in all his interviews with Pharaoh.    When the ransomed tribes fought their first battle with Amalek in Rephidim, Moses stood on a hill overlooking the scene of the conflict with the rod of God in his outstretched hand. On this occasion he was attended by Aaron and Hur, his sister's husband, who held up his wearied hands till Joshua and the chosen warriors of Israel gained the victory (  17:8-13  ).    Afterwards, when encamped before Sinai, and when Moses at the command of God ascended the mount to receive the tables of the law, Aaron and his two sons, Nadab and Abihu, along with seventy of the elders of Israel, were permitted to accompany him part of the way, and to behold afar off the manifestation of the glory of Israel's God (  Exodus 19:24  ;   24:9-11  ). While Moses remained on the mountain with God, Aaron returned unto the people; and yielding through fear, or ignorance, or instability of character, to their clamour, made unto them a golden calf, and set it up as an object of worship (  Exodus 32:4  ;   Psalms 106:19  ). On the return of Moses to the camp, Aaron was sternly rebuked by him for the part he had acted in this matter; but he interceded for him before God, who forgave his sin (  Deuteronomy 9:20  ).    On the mount, Moses received instructions regarding the system of worship which was to be set up among the people; and in accordance therewith Aaron and his sons were consecrated to the priest's office (  Leviticus 8  ;   9  ). Aaron, as high priest, held henceforth the prominent place appertaining to that office.    When Israel had reached Hazeroth, in \"the wilderness of Paran,\" Aaron joined with his sister Miriam in murmuring against Moses, \"because of the Ethiopian woman whom he had married,\" probably after the death of Zipporah. But the Lord vindicated his servant Moses, and punished Miriam with leprosy (  Numbers 12  ). Aaron acknowledged his own and his sister's guilt, and at the intercession of Moses they were forgiven.    Twenty years after this, when the children of Israel were encamped in the wilderness of Paran, Korah, Dathan, and Abiram conspired against Aaron and his sons; but a fearful judgment from God fell upon them, and they were destroyed, and the next day thousands of the people also perished by a fierce pestilence, the ravages of which were only stayed by the interposition of Aaron (  Numbers 16  ). That there might be further evidence of the divine appointment of Aaron to the priestly office, the chiefs of the tribes were each required to bring to Moses a rod bearing on it the name of his tribe. And these, along with the rod of Aaron for the tribe of Levi, were laid up overnight in the tabernacle, and in the morning it was found that while the other rods remained unchanged, that of Aaron \"for the house of Levi\" budded, blossomed, and yielded almonds (  Numbers 17:1-10  ). This rod was afterwards preserved in the tabernacle (  Hebrews 9:4  ) as a memorial of the divine attestation of his appointment to the priesthood.    Aaron was implicated in the sin of his brother at Meribah (  Numbers 20:8-13  ), and on that account was not permitted to enter the Promised Land. When the tribes arrived at Mount Hor, \"in the edge of the land of Edom,\" at the command of God Moses led Aaron and his son Eleazar to the top of that mountain, in the sight of all the people. There he stripped Aaron of his priestly vestments, and put them upon Eleazar; and there Aaron died on the top of the mount, being 123 years old (  Numbers 20:23-29  . Compare   Deuteronomy 10:6  ;   32:50  ), and was \"gathered unto his people.\" The people, \"even all the house of Israel,\" mourned for him thirty days. Of Aaron's sons two survived him, Eleazar, whose family held the high-priesthood till the time of Eli; and Ithamar, in whose family, beginning with Eli, the high-priesthood was held till the time of Solomon. Aaron's other two sons had been struck dead (  Leviticus 10:1   Leviticus 10:2  ) for the daring impiety of offering \"strange fire\" on the alter of incense.    The Arabs still show with veneration the traditionary site of Aaron's grave on one of the two summits of Mount Hor, which is marked by a Mohammedan chapel. His name is mentioned in the Koran, and there are found in the writings of the rabbins many fabulous stories regarding him.   He was the first anointed priest. His descendants, \"the house of Aaron,\" constituted the priesthood in general. In the time of David they were very numerous (  1\ufffdChronicles 12:27  ). The other branches of the tribe of Levi held subordinate positions in connection with the sacred office. Aaron was a type of Christ in his official character as the high priest. His priesthood was a \"shadow of heavenly things,\" and was intended to lead the people of Israel to look forward to the time when \"another priest\" would arise \"after the order of Melchizedek\" (  Hebrews 6:20  ). (See  MOSES )",
        "dictionaryText_ar": ""
    }
}
people_model_list = list(people_model['fields'].keys())
print(people_model_list)


with open(filename) as json_file:
    data = json.load(json_file)
    # print(type(data))
    # print(len(data))

    for index, item in enumerate(data):
        fields_list = list(item['fields'].keys())
        for key in people_model_list:
            if key in fields_list:
                pass
            else:
                print(key)

    print('end all')

# with open(results) as json_file:
#     data = json.load(json_file)
